spring.application.name=ThreatDefender
spring.datasource.url=jdbc:mysql://localhost:3306/threatdefender
spring.datasource.username=root
spring.datasource.password=@BaDhU8086930684
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver